pipeline {
    agent { label 'AGENT-1' }
    environment {
        PROJECT = 'EXPENSE'
        COMPONENT = 'BACKEND'
        DEPLOY_TO = "production"
    }
    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    stages {
        stage('Init') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('Apply or Destroy') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        if (params.ACTION == 'apply') {
                            sh """
                                cd 10-sg
                                terraform plan
                                terraform apply -auto-approve
                            """
                        } else {
                            sh """
                                cd 10-sg
                                terraform destroy -auto-approve
                            """
                        }
                    }
                }
            }
        }
        stage('Parallel Stages') {
            when {
                expression { params.ACTION == 'apply' }
            }
            parallel {
                stage('20-bastion') {
                    steps {
                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: 'apply')], propagate: true
                    }
                }
                stage('30-rds') {
                    steps {
                        build job: '30-rds', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('40-eks') {
                    steps {
                        build job: '40-eks', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('50-ecr') {
                    steps {
                        build job: '50-ecr', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'I will always say Hello again!'
            deleteDir()
        }
        failure {
            echo 'I will run when pipeline is failed'
        }
        success {
            echo 'I will run when pipeline is success'
        }
    }
}